# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163d5579968581806ba5b3c6780ea7701a4b0665046edc3cdcf6f083d56016ed02b6a1efbb5785b8ce84db35ea4a03785d9653ad387acaf4ac7a4fadcb118781

test:
  secret_key_base: 40b0b5cc0d65c81128d82f60a6c7d66c2a54f83784cfec736b2747760f12d4aea36b2d01f8bd9bdd6a407fc4381b5a196d9f2246901da54c2c2d7b300c11fa45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
